// Azure Resource Graph
// Azure Storage Blob - Misconfiguration Check
// https://www.linkedin.com/posts/activity-7184079321605529600-Obcd/

resources
| where type == "Microsoft.Storage/storageAccounts"
| extend allowBlobPublicAccess = parse_json(properties).allowBlobPublicAccess
| project subscriptionId, resourceGroup, name, allowBlobPublicAccess


// MITRE ATT&CK Mapping

// The query is primarily focused on identifying misconfigurations that could lead to unauthorized access. The relevant MITRE ATT&CK techniques include:
// T1530 - Data from Cloud Storage Object: This technique involves adversaries accessing data stored in cloud storage services. By identifying storage accounts with public blob access, you can detect potential exposure of sensitive data1.
