// Endpoint SMB exposed on Public Internet

// Actor Profile: Seashell Blizzard

// Seashell Blizzard (IRIDIUM) is a Russian cyber threat actor linked to the GRU. Active since 2013, they have conducted high-profile cyber attacks, including KillDisk, NotPetya, and FoxBlade. Their operations target critical infrastructure and support geopolitical objectives, using tools like Cobalt Strike and DarkCrystalRAT for espionage and sabotage.

// The following list has some of the vulnerabilities this group has exploited recently.

// CVE-2017-0143-Microsoft Server Message Block 1.0 (SMBv1)
// CVE-2017-0145-Microsoft Server Message Block 1.0 (SMBv1)

// I have provided a KQL detection for Endpoint SMB exposed on Public Internet for defenders to tighten their attack surface area against IRIDIUM

DeviceNetworkEvents
| where Timestamp > ago(30d)
| where ActionType == @"InboundConnectionAccepted"
| where LocalPort == "445"
| extend ExtractedIPv4 = extract(@"::ffff:(\d+\.\d+\.\d+\.\d+)$", 1, LocalIP) // Parse IPv4 address when LocalIPType == "FourToSixMapping"
| where RemoteIPType == "Public"
| where LocalIPType == "Public" or
    (LocalIPType == "FourToSixMapping" and
     isnotempty(ExtractedIPv4) and  //Ignore if ExtractedIPv4 is null meaning it was not FourToSixMapping
     not(ipv4_is_private(ExtractedIPv4))
    )



// Mitre ATT&CK
