// MailItemsAccessed Defense
// https://www.linkedin.com/posts/0x534c_microsoft365-exchangeonline-defenderxdr-activity-7183335339061620738-ztfq/

// Simple & effective custom DefenderXDR hourly rule to detect threat actors accessing Exchange mailboxes via MailItemsAccessed log entry and marked user as compromised.

CloudAppEvents
| where Timestamp > ago(1h)
| where IPTags has_any ("Brute force attacker",
"Password spray attacker", "Malicious", "Tor")
| where ActionType == "MailItemsAccessed"


// MITRE ATT&CK Mapping

// Your KQL query is effectively filtering for events that could indicate various forms of credential access and email collection attacks, which are mapped to the following MITRE ATT&CK techniques:

// T1110 - Brute Force
// T1110.003 - Password Spraying
// T1078 - Valid Accounts
// T1071 - Application Layer Protocol
// T1090.003 - Proxy: Multi-hop Proxy
// T1114 - Email Collection
