// Azure CLI Spray - ASN 53667
// https://www.linkedin.com/posts/activity-7216141179648716800-703J/

// Defenders take note of this ASN using IPV6 to conduct Azure CLI Spray on your Entra Tenant. Use the below KQL to check against you Sentinel.🤝

// ASN 53667 Lookup - https://lnkd.in/gAVK5htd

SigninLogs
| where TimeGenerated > ago(30d)
| where ResultType == "50126" or ResultType == "50053"
| where UserAgent == "node-fetch"
| where AutonomousSystemNumber == "53667"
| where AppDisplayName == "Microsoft Azure CLI"

// MITRE ATT&CK Mapping

// Based on the criteria in the KQL query, the following MITRE ATT&CK techniques are relevant:

// T1078 - Valid Accounts: The query is looking for failed sign-in attempts, which can indicate attempts to use valid accounts with incorrect credentials.
// T1071.001 - Application Layer Protocol: Web Protocols: The use of “node-fetch” suggests web-based communication, which falls under this technique.
// T1586.001 - Compromise Infrastructure: Botnet: The specific ASN and user agent might indicate the use of compromised infrastructure or botnets for automated sign-in attempts.
// T1078.004 - Valid Accounts: Cloud Accounts: The use of “Microsoft Azure CLI” indicates attempts to access cloud resources, which is relevant to this technique.
