//Detecting Nation State Actors @ Near Realtime
//https://www.linkedin.com/feed/update/urn:li:activity:7172463683351113728/

//In view of recent updates from Microsoft on Midnight Blizzard, for those on Microsoft Entra ID P2 running the below Sentinel KQL analytic rule at NRT (Near real-time) will give you the best detection if your tenant is impacted by any nation state actors based on Microsoft Security Intelligence (MSTIC) telemetry data. 

AADUserRiskEvents
| where RiskEventType == "nationStateIP"


// MITRE ATT&CK Mapping

// Based on the operations and objectives of the KQL code, the following MITRE ATT&CK techniques are relevant:

// Technique ID: T1071.001 - Application Layer Protocol: Web Protocols: This technique involves adversaries using web protocols to communicate with systems under their control. Nation-state actors often use such methods to gain initial access to systems1.
// Technique ID: T1078.004 - Valid Accounts: Cloud Accounts: This technique involves adversaries using valid cloud accounts to gain access. Nation-state actors may use compromised cloud accounts to infiltrate systems2.
