// Detect Microsoft Graph API Abuse
// Linkedin Post: https://www.linkedin.com/posts/0x534c_nation-state-attackers-increasingly-abuse-activity-7227945393827815424-QMVG/
// This offline risk detection is reported when abnormal GraphAPI traffic or directory enumeration is observed. Suspicious API traffic might suggest that a user is compromised and conducting reconnaissance in the environment.

// ** A premium detection requiring Entra P2 license **

search in (SigninLogs, AADUserRiskEvents, AADNonInteractiveUserSignInLogs)
TimeGenerated between (ago(48h) .. now())
and (
RiskEventTypes == "suspiciousAPITraffic"
)

// Reference: https://learn.microsoft.com/en-us/entra/id-protection/concept-identity-protection-risks#suspicious-api-traffic

// MITRE ATT&CK Mapping

// Based on the operations and objectives of the KQL code, the following MITRE ATT&CK techniques are relevant:

// T1078 - Valid Accounts: Attackers may use valid accounts to access and interact with systems, which can generate suspicious API traffic.
// T1071 - Application Layer Protocol: Suspicious API traffic might indicate the use of application layer protocols for command and control.
// T1070 - Indicator Removal on Host: Attackers might try to hide their tracks by generating suspicious API traffic to remove indicators from logs.
// T1059 - Command and Scripting Interpreter: Suspicious API traffic could be a result of scripts or commands executed by the attacker.
